FROM openjdk:19
EXPOSE 80
ADD ./target/WebInterface-1.0-SNAPSHOT-jar-with-dependencies.jar WebInterface-1.0-SNAPSHOT-jar-with-dependencies.jar
ENTRYPOINT ["java","-jar", "WebInterface-1.0-SNAPSHOT-jar-with-dependencies.jar"]